"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "@/styles/global.scss";

const inter = Inter({ subsets: ["latin"] });
import { store, persistor } from "@/store/store.ts";
import { Provider } from "react-redux";

import App from "@/App";
import { SessionProvider } from "next-auth/react";
import { PersistGate } from "redux-persist/integration/react";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  session,
}: Readonly<{
  children: React.ReactNode;
  session?: any;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            <SessionProvider session={session}>
              <App>{children}</App>
            </SessionProvider>
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
