"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";
import { useRef } from "react";
import { Sidebar, Topbar, PageCard } from "@/components";
import { AppContextProvider } from "@/providers/contextProvider";
import "@/styles/global.scss";

const inter = Inter({ subsets: ["latin"] });
import { store } from "@/store/store.ts";
import { Provider } from "react-redux";
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const refPage = useRef<any>();
  const pathName = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <AppContextProvider currentPath={pathName}>
            <main className="main-container">
              <Sidebar />

              <section className="main-wrapper">
                <Topbar />
                <div className="page-container">
                  <PageCard ref={refPage}>{children}</PageCard>
                </div>
              </section>
            </main>
          </AppContextProvider>
        </Provider>
      </body>
    </html>
  );
}
