export default {
  keyCode: {
    backspace: 8,
    space: 32,
    keyA: 65,
    keyB: 66,
    keyC: 67,
    keyD: 68,
    keyE: 69,
    keyF: 70,
    keyG: 71,
    keyH: 72,
    keyI: 73,
    keyJ: 74,
    keyK: 75,
    keyL: 76,
    keyM: 77,
    keyN: 78,
    keyO: 79,
    keyP: 80,
    keyQ: 81,
    keyR: 82,
    keyS: 83,
    keyT: 84,
    keyU: 85,
    keyV: 86,
    keyW: 87,
    keyX: 88,
    keyY: 89,
    keyZ: 90,
  },
  keyMap: {
    8: { label: "<-", class: "backspace", noText: true },
    32: { label: "Space", class: "space", char: " " },
    65: { label: "A", char: "a" },
    66: { label: "B", char: "b" },
    67: { label: "C", char: "c" },
    68: { label: "D", char: "d" },
    69: { label: "E", char: "e" },
    70: { label: "F", char: "f" },
    71: { label: "G", char: "g" },
    72: { label: "H", char: "h" },
    73: { label: "I", char: "i" },
    74: { label: "J", char: "j" },
    75: { label: "K", char: "k" },
    76: { label: "L", char: "l" },
    77: { label: "M", char: "m" },
    78: { label: "N", char: "n" },
    79: { label: "O", char: "o" },
    80: { label: "P", char: "p" },
    81: { label: "Q", char: "q" },
    82: { label: "R", char: "r" },
    83: { label: "S", char: "s" },
    84: { label: "T", char: "t" },
    85: { label: "U", char: "u" },
    86: { label: "V", char: "v" },
    87: { label: "W", char: "w" },
    88: { label: "X", char: "x" },
    89: { label: "Y", char: "y" },
    90: { label: "Z", char: "z" },
  },
};
