export default {
  tr: {
    rows: [
      {
        keyQ: 81,
        keyW: 87,
        keyE: 69,
        keyR: 82,
        keyT: 84,
        keyY: 89,
        keyU: 85,
        keyI: 73,
        keyO: 79,
        keyP: 80,
        keyG_tr: 219,
        keyU_tr: 221,
      },
      {
        keyA: 65,
        keyS: 83,
        keyD: 68,
        keyF: 70,
        keyG: 71,
        keyH: 72,
        keyJ: 74,
        keyK: 75,
        keyL: 76,
        keyS_tr: 186,
        keyI_tr: 222,
      },
      {
        keyZ: 90,
        keyX: 88,
        keyC: 67,
        keyV: 86,
        keyB: 66,
        keyN: 78,
        keyM: 77,
        keyO_tr: 191,
        keyC_tr: 220,
      },
      {
        space: 32,
      },
    ],
  },
  keyCode: {
    backspace: 8,
    space: 32,
    keyA: 65,
    keyB: 66,
    keyC: 67,
    keyD: 68,
    keyE: 69,
    keyF: 70,
    keyG: 71,
    keyH: 72,
    keyI: 73,
    keyJ: 74,
    keyK: 75,
    keyL: 76,
    keyM: 77,
    keyN: 78,
    keyO: 79,
    keyP: 80,
    keyQ: 81,
    keyR: 82,
    keyS: 83,
    keyT: 84,
    keyU: 85,
    keyV: 86,
    keyW: 87,
    keyX: 88,
    keyY: 89,
    keyZ: 90,
    keyO_tr: 191,
    keyC_tr: 220,
    keyS_tr: 186,
    keyI_tr: 222,
    keyG_tr: 219,
    keyU_tr: 221,
  },
  keyMap: {
    8: { label: "<-", class: "backspace", noText: true },
    32: { label: "Space", class: "space", char: " ", char_tr: " " },
    65: { label: "A", char: "a", char_tr: "a" },
    66: { label: "B", char: "b", char_tr: "b" },
    67: { label: "C", char: "c", char_tr: "c" },
    68: { label: "D", char: "d", char_tr: "d" },
    69: { label: "E", char: "e", char_tr: "e" },
    70: { label: "F", char: "f", char_tr: "f" },
    71: { label: "G", char: "g", char_tr: "g" },
    72: { label: "H", char: "h", char_tr: "h" },
    73: { label: "I", char: "i", char_tr: "ı" },
    74: { label: "J", char: "j", char_tr: "j" },
    75: { label: "K", char: "k", char_tr: "k" },
    76: { label: "L", char: "l", char_tr: "l" },
    77: { label: "M", char: "m", char_tr: "m" },
    78: { label: "N", char: "n", char_tr: "n" },
    79: { label: "O", char: "o", char_tr: "o" },
    80: { label: "P", char: "p", char_tr: "p" },
    81: { label: "Q", char: "q", char_tr: "q" },
    82: { label: "R", char: "r", char_tr: "r" },
    83: { label: "S", char: "s", char_tr: "s" },
    84: { label: "T", char: "t", char_tr: "t" },
    85: { label: "U", char: "u", char_tr: "u" },
    86: { label: "V", char: "v", char_tr: "v" },
    87: { label: "W", char: "w", char_tr: "w" },
    88: { label: "X", char: "x", char_tr: "x" },
    89: { label: "Y", char: "y", char_tr: "y" },
    90: { label: "Z", char: "z", char_tr: "z" },
    191: { label: "Ö", char: "ö", char_tr: "ö" },
    220: { label: "Ç", char: "ç", char_tr: "ç" },
    186: { label: "Ş", char: "ş", char_tr: "ş" },
    222: { label: "İ", char: "i", char_tr: "i" },
    219: { label: "Ğ", char: "ğ", char_tr: "ğ" },
    221: { label: "Ü", char: "ü", char_tr: "ü" },
  },
};
